baseurl = "https://maciejkula.github.io"
languageCode = "en-us"
title = "Mostly Engineering"
# theme = "cocoa-eh-hugo-theme"
# theme = "hugo-xmin"
theme = "er"
# theme = "hugo-lithium-theme"
# theme = "hugo-natrium-theme"
# theme = "hugo-cactus-theme"
googleAnalytics = "UA-33073489-2"
disqusShortname = "maciejkula"
pygmentsCodeFences = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Github"
    url = "https://github.com/maciejkula/"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Maciej_Kula"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    showTagCloud = false
    footer = "Maciej Kula | [Github](https://github.com/maciejkula) | [Twitter](https://twitter.com/Maciej_Kula)"
    enableRSS = true
