baseurl = "https://maciejkula.github.io"
languageCode = "en-us"
title = "Mostly Engineering"
# theme = "cocoa-eh-hugo-theme"
theme = "hugo-xmin"
# theme = "hugo-lithium-theme"
# theme = "hugo-natrium-theme"
# theme = "hugo-cactus-theme"
googleAnalytics = "UA-33073489-2"
disqusShortname = "maciejkula"
pygmentsCodeFences = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    footer = "Maciej Kula | [Github](https://github.com/maciejkula) | [Twitter](https://twitter.com/Maciej_Kula)"
    name = "John Doe"
	description = "Describe your website"
	bio = "Blogger & Programmer"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
    enableRSS = true
